bindPort = 7000
allowPorts = [
  { start = 10000, end = 30000 },
]
webServer.addr = "0.0.0.0"
webServer.port = 7001
webServer.user = "NingMeng123"
webServer.password = "NingMeng080317"
vhostHTTPPort = 80
[[httpPlugins]]
addr = "http://127.0.0.1:8080"
path = "/"
ops = ["NewProxy", "CloseProxy"]