.PHONY: install build-frpc build-frps dev-frpc dev-frps clean

install:
	@pnpm install

build-frpc:
	@pnpm run build:frpc

build-frps:
	@pnpm run build:frps

dev-frpc:
	@pnpm run dev:frpc

dev-frps:
	@pnpm run dev:frps

clean:
	@pnpm run clean 